---
- name: Proxmox - Import Cloud Image Only
  hosts: all
  connection: local
  gather_facts: false

  vars:
    pve_password: "{{ PROXMOX_PASSWORD }}"

  tasks:
    # --------------------------------------------------------------------------
    # 0. VALIDATION
    # --------------------------------------------------------------------------
    - name: Validate Required Inputs
      ansible.builtin.debug:
        msg: "Validating inputs..."
      vars:
        check_node: "{{ target_node | mandatory }}"
        check_store: "{{ storage | mandatory }}"
        check_url: "{{ image_url | mandatory }}"
        check_name: "{{ image_filename | mandatory }}"

    - name: "Debug: Configuration Review"
      debug:
        msg: 
          - "Target Node:     {{ target_node }}"
          - "Target Storage:  {{ storage }}"
          - "Download URL:    {{ image_url }}"
          - "Save As:         {{ image_filename }}"

    # --------------------------------------------------------------------------
    # 1. DOWNLOAD IMAGE (API)
    # --------------------------------------------------------------------------
    - name: Trigger Remote Download (to {{ storage }})
      ansible.builtin.uri:
        # API: /nodes/{node}/storage/{storage}/download-url
        url: "https://{{ ansible_host }}:8006/api2/json/nodes/{{ target_node }}/storage/{{ storage }}/download-url"
        method: POST
        validate_certs: false
        headers:
          Authorization: "PVEAPIToken={{ ansible_user }}={{ pve_password }}"
        body_format: json
        body:
          content: "iso" # 'iso' is the standard content type for image files in this API
          filename: "{{ image_filename }}"
          url: "{{ image_url }}"
      register: download_task
      changed_when: true

    # --------------------------------------------------------------------------
    # 2. MONITOR DOWNLOAD
    # --------------------------------------------------------------------------
    - name: Wait for Download to Finish
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8006/api2/json/nodes/{{ target_node }}/tasks/{{ download_task.json.data }}/status"
        method: GET
        validate_certs: false
        headers:
          Authorization: "PVEAPIToken={{ ansible_user }}={{ pve_password }}"
      register: task_status
      # Check status every 10s, wait up to 20 minutes
      until: task_status.json.data.status == "stopped"
      retries: 120
      delay: 10
      failed_when: 
        - task_status.json.data.status == "stopped" 
        - task_status.json.data.exitstatus != "OK"

    - name: Report Success
      ansible.builtin.debug:
        msg: "Image successfully downloaded to {{ storage }}:iso/{{ image_filename }}"