---
- name: Install Proxmox/QEMU Guest Agent
  hosts: all
  remote_user: ansible
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
      register: agent_install

    - name: Ensure qemu-guest-agent is started and enabled
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes

    # The agent sometimes needs a nudge to start talking to the host immediately
    - name: Restart agent to ensure immediate connectivity
      service:
        name: qemu-guest-agent
        state: restarted
      when: agent_install.changed
