---
- name: Install Default GUI (Universal & Verification Based)
  hosts: all
  become: yes
  gather_facts: yes

  # --- 1. THE GATEKEEPER ---
  roles:
    - os_gatekeeper  # Reuses your logic to fail if RHEL is unregistered

  vars:
    gui_marker_map:
      Debian: "gnome-session"
      Ubuntu: "ubuntu-desktop" 
      RedHat: "gdm"
      Rocky: "gdm"
      AlmaLinux: "gdm"

  tasks:
    # ---------------------------------------------------------
    # 2. VERIFICATION: CHECK REAL INSTALLED PACKAGES
    # ---------------------------------------------------------
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if GUI is already installed
      ansible.builtin.set_fact:
        gui_is_installed: "{{ gui_marker_map[ansible_distribution] in ansible_facts.packages }}"
      when: ansible_distribution in gui_marker_map

    - name: Stop if GUI software is already present
      ansible.builtin.meta: end_host
      when: gui_is_installed | default(false) | bool

    # ---------------------------------------------------------
    # 3. SUSE HANDLING
    # ---------------------------------------------------------
    - name: End play for SUSE
      ansible.builtin.meta: end_host
      when: ansible_os_family == 'Suse'

    # ---------------------------------------------------------
    # 4. INSTALLATION: DEBIAN FAMILY
    # ---------------------------------------------------------
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install Desktop Environment (Ubuntu)
      ansible.builtin.apt:
        name: ubuntu-desktop
        state: present
      register: deb_install
      when: ansible_distribution == 'Ubuntu'

    - name: Install Desktop Environment (Debian)
      ansible.builtin.apt:
        name: task-gnome-desktop
        state: present
      register: deb_install
      when: ansible_distribution == 'Debian'

    # ---------------------------------------------------------
    # 5. INSTALLATION: RHEL FAMILY (RHEL, Rocky, Alma)
    # ---------------------------------------------------------
    - name: Install Desktop Group (RHEL/Rocky/Alma)
      ansible.builtin.dnf:
        name: "@Server with GUI"
        state: present
      register: rhel_install
      when: ansible_os_family == 'RedHat'

    # ---------------------------------------------------------
    # 6. CONFIGURATION & REBOOT
    # ---------------------------------------------------------
    - name: Ensure boot target is set to graphical
      ansible.builtin.systemd:
        name: graphical.target
        enabled: yes
        masked: no

    - name: Set default target to graphical
      ansible.builtin.file:
        src: /lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
        force: yes

    - name: Reboot to initialize Desktop Environment
      ansible.builtin.reboot:
        msg: "Rebooting to initialize GUI"
      when: (deb_install is changed) or (rhel_install is changed)