---
- name: Install Default GUI (Universal & Verification Based)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # We define a "Marker Package" for each OS. 
    # If this package is present, we assume the GUI is fully installed.
    # Debian/Ubuntu: gnome-session is the core session manager.
    # RHEL/Rocky: gdm is the Gnome Display Manager (standard for Server GUI).
    gui_marker_map:
      Debian: "gnome-session"
      Ubuntu: "ubuntu-desktop" 
      RedHat: "gdm"
      Rocky: "gdm"
      AlmaLinux: "gdm"

  tasks:
    # ---------------------------------------------------------
    # 1. VERIFICATION: CHECK REAL INSTALLED PACKAGES
    # ---------------------------------------------------------
    - name: Gather the package facts (Check what is actually installed)
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if GUI is already installed (OS Agnostic)
      ansible.builtin.set_fact:
        gui_is_installed: "{{ gui_marker_map[ansible_distribution] in ansible_facts.packages }}"
      ignore_errors: yes # Gracefully handle OS detection weirdness

    - name: Stop if GUI software is already present
      block:
        - name: Verify existing GUI
          ansible.builtin.debug:
            msg: "GUI Package ({{ gui_marker_map[ansible_distribution] }}) is already installed. Skipping."
        
        - name: End play for this host
          ansible.builtin.meta: end_host
      when: gui_is_installed | bool

    # ---------------------------------------------------------
    # 2. SUSE HANDLING (Skip Logic)
    # ---------------------------------------------------------
    - name: Handle SUSE Enterprise Linux
      block:
        - name: Log SUSE skip
          ansible.builtin.debug:
            msg: "SUSE detected. Assuming GUI is managed by system defaults/YaST. Skipping."
        - name: End play for SUSE
          ansible.builtin.meta: end_host
      when: ansible_os_family == 'Suse'

    # ---------------------------------------------------------
    # 3. INSTALLATION: DEBIAN FAMILY
    # ---------------------------------------------------------
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install Desktop Environment (Ubuntu)
      ansible.builtin.apt:
        name: ubuntu-desktop
        state: present
      register: deb_install
      when: ansible_distribution == 'Ubuntu'

    - name: Install Desktop Environment (Debian)
      ansible.builtin.apt:
        name: task-gnome-desktop
        state: present
      register: deb_install
      when: ansible_distribution == 'Debian'

    # ---------------------------------------------------------
    # 4. INSTALLATION: RHEL FAMILY
    # ---------------------------------------------------------
    - name: Install Desktop Group (RHEL/Rocky/Alma)
      ansible.builtin.dnf:
        name: "@Server with GUI"
        state: present
      register: rhel_install
      when: ansible_os_family == 'RedHat'

    # ---------------------------------------------------------
    # 5. CONFIGURATION & REBOOT
    # ---------------------------------------------------------
    # We force the link even if it existed before, because now we KNOW the software is there.
    - name: Ensure boot target is set to graphical
      ansible.builtin.systemd:
        name: graphical.target
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Reboot to initialize Desktop Environment
      ansible.builtin.reboot:
        msg: "Rebooting system to initialize Desktop Environment"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 5
      when: >
        (deb_install is changed) or 
        (rhel_install is changed)
