---
- name: Create Sudo User (Universal - Debian/RHEL/SUSE)
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # These will be overridden by Semaphore Extra Vars
    new_username: "defaultuser"
    new_password: "changeme"
    admin_group_map:
      Debian: "sudo"
      RedHat: "wheel"
      Suse: "wheel"

  tasks:
    - name: Ensure sudo package is installed
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Enable wheel group in sudoers (SUSE only)
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel ALL='
        line: '%wheel ALL=(ALL:ALL) ALL'
        validate: 'visudo -cf %s'
      when: ansible_os_family == 'Suse'

    - name: Create the user account
      ansible.builtin.user:
        name: "{{ new_username }}"
        password: "{{ new_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: "{{ admin_group_map[ansible_os_family] | default('sudo') }}"
        append: yes
        create_home: yes
        state: present
