---
- name: Install Default GUI (Universal)
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - os_gatekeeper  # Still ensures RHEL is registered first

  vars:
    gui_marker_map:
      Debian: "gnome-session"
      Ubuntu: "ubuntu-desktop" 
      RedHat: "gdm"
      Rocky: "gdm"
      AlmaLinux: "gdm"
      SLES: "gnome-session"
      openSUSE: "gnome-session"

  tasks:
    # ---------------------------------------------------------
    # 1. VERIFICATION: CHECK SOFTWARE & BOOT TARGET
    # ---------------------------------------------------------
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check current boot target
      ansible.builtin.command: systemctl get-default
      register: current_target
      changed_when: false

    - name: Determine if GUI is fully ready
      ansible.builtin.set_fact:
        gui_fully_configured: >-
          {{ 
            (ansible_distribution in gui_marker_map and gui_marker_map[ansible_distribution] in ansible_facts.packages) and 
            (current_target.stdout == 'graphical.target') 
          }}

    - name: Stop if GUI software is present AND target is graphical
      ansible.builtin.meta: end_host
      when: gui_fully_configured | default(false) | bool

    # ---------------------------------------------------------
    # 2. INSTALLATION: DEBIAN/UBUNTU
    # ---------------------------------------------------------
    - name: Install Desktop (Ubuntu/Debian)
      ansible.builtin.apt:
        name: "{{ 'ubuntu-desktop' if ansible_distribution == 'Ubuntu' else 'task-gnome-desktop' }}"
        state: present
      register: deb_install
      when: ansible_os_family == 'Debian'

    # ---------------------------------------------------------
    # 3. INSTALLATION: RHEL FAMILY
    # ---------------------------------------------------------
    - name: Install Desktop Group (RHEL Family)
      ansible.builtin.dnf:
        name: "@Server with GUI"
        state: present
      register: rhel_install
      when: ansible_os_family == 'RedHat'

    # ---------------------------------------------------------
    # 4. INSTALLATION: SUSE FAMILY
    # ---------------------------------------------------------
    - name: Install Gnome Pattern (SUSE)
      community.general.zypper:
        name: 'patterns-gnome-gnome_basic'
        type: pattern
        state: present
      register: suse_install
      when: ansible_os_family == 'Suse'

    # ---------------------------------------------------------
    # 5. CONFIGURATION & REBOOT
    # ---------------------------------------------------------
    - name: Set default boot target to graphical
      ansible.builtin.command: systemctl set-default graphical.target
      register: target_change
      changed_when: current_target.stdout != 'graphical.target'

    - name: Ensure graphical target is active
      ansible.builtin.systemd:
        name: graphical.target
        state: started
        enabled: yes

    - name: Reboot if changes were made
      ansible.builtin.reboot:
        msg: "Applying graphical interface changes."
      when: >
        (deb_install is changed) or 
        (rhel_install is changed) or 
        (suse_install is changed) or
        (target_change is changed)