---
- name: Update Ansible User Display Name
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # HARDCODED: The actual username you log in with (e.g., 'ansible', 'cloud-user', etc.)
    target_username: "ansible"
    
    # The new "Full Name" you want to see on the Login Screen
    new_display_name: "Ansible"

  tasks:
    # --------------------------------------------------------------------------
    # 0. SAFETY CHECK
    # --------------------------------------------------------------------------
    - name: Verify target user exists
      ansible.builtin.getent:
        database: passwd
        key: "{{ target_username }}"
      register: user_check
      ignore_errors: true

    - name: Fail if user not found
      ansible.builtin.fail:
        msg: "User '{{ target_username }}' does not exist on this system!"
      when: user_check.failed

    # --------------------------------------------------------------------------
    # 1. UPDATE USER COMMENT (GECOS)
    # --------------------------------------------------------------------------
    - name: Change user description to '{{ new_display_name }}'
      ansible.builtin.user:
        name: "{{ target_username }}"
        comment: "{{ new_display_name }}"
        # 'state: present' ensures we modify the existing user rather than recreating it
        state: present
      register: user_update

    # --------------------------------------------------------------------------
    # 2. VERIFICATION
    # --------------------------------------------------------------------------
    - name: Verify the change in /etc/passwd
      ansible.builtin.getent:
        database: passwd
        key: "{{ target_username }}"
      register: check_user_final

    - name: Display updated user details
      ansible.builtin.debug:
        msg: 
          - "User: {{ target_username }}"
          - "Old Name: {{ user_check.ansible_facts.getent_passwd[target_username][4] }}"
          - "New Name: {{ check_user_final.ansible_facts.getent_passwd[target_username][4] }}"