---
- name: Test Proxmox Connectivity (Using Inventory)
  # 1. Target the 'all' group or a specific group from your inventory
  hosts: all
  
  # 2. IMPORTANT: Run tasks on Semaphore, not via SSH on the Proxmox server
  connection: local
  gather_facts: false

  vars:
    # We still use the Secret for the password to ensure it works reliably
    # regardless of how Semaphore injects SSH credentials.
    pve_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"

  tasks:
    - name: Debug Inventory Data
      debug:
        msg: 
          - "Targeting Host from Inventory: {{ inventory_hostname }}"
          - "Using IP: {{ ansible_host }}"
          - "Using User: {{ ansible_user }}"

    - name: Connect to Proxmox
      community.general.proxmox_query:
        # 3. Map Inventory Variables to API Parameters
        api_host: "{{ ansible_host }}"  # The IP defined in Inventory
        api_user: "{{ ansible_user }}"  # The User defined in Inventory
        api_password: "{{ pve_password }}" # The Secret Variable
        node: "{{ inventory_hostname }}"   # Assumes inventory alias matches Proxmox Node name
        validate_certs: false
        query: version
      register: pve_version

    - name: Display Result
      debug:
        msg: "Successfully connected to {{ inventory_hostname }} running version {{ pve_version.response.version }}"