---
- name: Test Proxmox Connectivity (Using Module)
  hosts: all
  connection: local
  gather_facts: false

  vars:
    pve_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"

  tasks:
    - name: Debug Inventory Data
      debug:
        msg: 
          - "Targeting Host: {{ inventory_hostname }}"
          - "API Host: {{ ansible_host }}"
          - "Full User String: {{ ansible_user }}"

    - name: Connect to Proxmox and Get Node Info
      community.proxmox.proxmox_node_info:
        api_host: "{{ ansible_host }}"
        # Split 'ansible@pve!ansible-token' into 'ansible@pve'
        api_user: "{{ ansible_user.split('!')[0] }}"
        # Split 'ansible@pve!ansible-token' into 'ansible-token'
        api_token_id: "{{ ansible_user.split('!')[1] }}"
        api_token_secret: "{{ pve_password }}"
        validate_certs: false
      register: pve_info

    - name: Display Found Nodes
      debug:
        msg: "Found Nodes: {{ pve_info.proxmox_nodes | map(attribute='node') | list }}"
