---
- name: Proxmox - Download Image & Create Template
  hosts: all
  connection: local
  gather_facts: false

  vars:
    # Secrets
    pve_password: "{{ PROXMOX_PASSWORD }}"

  tasks:
    # ==========================================================================
    # 0. VALIDATION & SETUP
    # ==========================================================================
    - name: Validate Required Inputs
      ansible.builtin.debug:
        msg: "Validating inputs..."
      vars:
        check_node: "{{ target_node | mandatory }}"
        check_store: "{{ storage | mandatory }}"
        check_url: "{{ image_url | mandatory }}"
        check_file: "{{ image_filename | mandatory }}"
        check_id: "{{ template_id | mandatory }}"
        check_name: "{{ vm_name | mandatory }}"
        check_pool: "{{ resource_pool | mandatory }}"

    - name: "Debug: Configuration Review"
      debug:
        msg: 
          - "Target Node:     {{ target_node }}"
          - "Storage:         {{ storage }}"
          - "Download URL:    {{ image_url }}"
          - "Filename:        {{ image_filename }}"
          - "Template ID:     {{ template_id }}"
          - "Template Name:   {{ vm_name }}"

    # ==========================================================================
    # 1. DOWNLOAD IMAGE (API)
    # ==========================================================================
    - name: Trigger Remote Download (to {{ storage }})
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8006/api2/json/nodes/{{ target_node }}/storage/{{ storage }}/download-url"
        method: POST
        validate_certs: false
        headers:
          Authorization: "PVEAPIToken={{ ansible_user }}={{ pve_password }}"
        body_format: json
        body:
          # Use 'import' content type for raw disk images (qcow2/img)
          content: "import"
          filename: "{{ image_filename }}"
          url: "{{ image_url }}"
      register: download_task
      changed_when: true

    - name: Wait for Download to Finish
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8006/api2/json/nodes/{{ target_node }}/tasks/{{ download_task.json.data }}/status"
        method: GET
        validate_certs: false
        headers:
          Authorization: "PVEAPIToken={{ ansible_user }}={{ pve_password }}"
      register: task_status
      # Check status every 10s, wait up to 20 minutes
      until: task_status.json.data.status == "stopped"
      retries: 120
      delay: 10
      failed_when: 
        - task_status.json.data.status == "stopped" 
        - task_status.json.data.exitstatus != "OK"

    - name: Download Verification
      ansible.builtin.debug:
        msg: "Download complete. Proceeding to VM creation using {{ storage }}:import/{{ image_filename }}"

    # ==========================================================================
    # 2. CLEANUP OLD VM
    # ==========================================================================
    - name: Destroy existing VM/Template (ID {{ template_id }})
      community.proxmox.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user.split('!')[0] }}"
        api_token_id: "{{ ansible_user.split('!')[1] }}"
        api_token_secret: "{{ pve_password }}"
        node: "{{ target_node }}"
        vmid: "{{ template_id }}"
        state: absent
      failed_when: false 

    # ==========================================================================
    # 3. CREATE VM & IMPORT DISK
    # ==========================================================================
    - name: Create VM from Downloaded Image
      community.proxmox.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user.split('!')[0] }}"
        api_token_id: "{{ ansible_user.split('!')[1] }}"
        api_token_secret: "{{ pve_password }}"
        node: "{{ target_node }}"
        vmid: "{{ template_id }}"
        name: "{{ vm_name }}"
        pool: "{{ resource_pool }}"
        
        # Hardware Config
        memory: "{{ vm_memory | default(2048) }}"
        cores: "{{ vm_cores | default(2) }}"
        cpu: host
        net:
          net0: "virtio,bridge={{ vm_bridge | default('vmbr0') }}"
        scsihw: virtio-scsi-pci
        
        # Import the file we just downloaded
        # Syntax: STORAGE:import/FILENAME
        scsi:
          scsi0: "{{ storage }}:0,import-from={{ storage }}:import/{{ image_filename }},ssd=1,discard=on"
        
        ide:
          ide2: "{{ storage }}:cloudinit"
        boot: "order=scsi0"
        
        ostype: l26
        vga: std
        agent: "enabled=1,fstrim_cloned_disks=1"
        hotplug: "disk,network,usb,memory,cpu"
        
        state: present
        timeout: 300

    # ==========================================================================
    # 4. CONFIGURATION FIXES (NUMA)
    # ==========================================================================
    - name: Enable NUMA (API Workaround)
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}:8006/api2/json/nodes/{{ target_node }}/qemu/{{ template_id }}/config"
        method: POST
        validate_certs: false
        headers:
          Authorization: "PVEAPIToken={{ ansible_user }}={{ pve_password }}"
        body_format: json
        body:
          numa: 1
      changed_when: true

    # ==========================================================================
    # 5. FINALIZE (CONVERT TO TEMPLATE)
    # ==========================================================================
    - name: Convert VM {{ template_id }} to Template
      community.proxmox.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user.split('!')[0] }}"
        api_token_id: "{{ ansible_user.split('!')[1] }}"
        api_token_secret: "{{ pve_password }}"
        node: "{{ target_node }}"
        vmid: "{{ template_id }}"
        template: true