---
- name: Test Proxmox Connectivity
  hosts: all
  connection: local
  gather_facts: false

  vars:
    pve_password: "{{ PROXMOX_PASSWORD }}"

#proxmoxer installed via apt install python3-proxmoxer python3-requests for system wide availability

  tasks:
    - name: Connect to Proxmox and Get Node Info
      community.proxmox.proxmox_node_info:
        api_host: "{{ ansible_host }}"
        api_user: "{{ ansible_user.split('!')[0] }}"
        api_token_id: "{{ ansible_user.split('!')[1] }}"
        api_token_secret: "{{ pve_password }}"
        validate_certs: false
      register: pve_info

    - name: Display Found Nodes
      debug:
        msg: "Found Nodes: {{ pve_info.proxmox_nodes | map(attribute='node') | list }}"
