---
- name: OS-Specific Update Management
  hosts: all
  become: yes
  
  roles:
    - os_gatekeeper  
  tasks:
    - name: Install all updates (DNF)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      # This runs for RHEL (if it passed the role) and Rocky/CentOS automatically
      when: ansible_os_family == "RedHat"