---
- name: Set Universal Keyboard Layout to UK
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # ==============================================================================
    # 1. DEBIAN / UBUNTU / KALI
    #    Target: /etc/default/keyboard
    #    Helper: console-setup
    # ==============================================================================
    - name: Handle Debian/Ubuntu Family
      when: ansible_os_family == "Debian"
      block:
        - name: Ensure 'console-setup' is installed
          ansible.builtin.apt:
            name: console-setup
            state: present
            update_cache: yes
            cache_valid_time: 3600

        - name: Set XKBLAYOUT to gb in /etc/default/keyboard
          ansible.builtin.lineinfile:
            path: /etc/default/keyboard
            regexp: '^XKBLAYOUT='
            line: 'XKBLAYOUT="gb"'
            create: yes
            mode: '0644'
          notify: Refresh Debian Console

    # ==============================================================================
    # 2. REDHAT / ROCKY / SUSE
    #    Target: /etc/vconsole.conf
    #    Helper: loadkeys (part of kbd package, usually default)
    # ==============================================================================
    - name: Handle RedHat/Suse Family
      when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"
      block:
        - name: Set KEYMAP to uk in /etc/vconsole.conf
          ansible.builtin.lineinfile:
            path: /etc/vconsole.conf
            regexp: '^KEYMAP='
            line: 'KEYMAP="uk"'
            create: yes
            mode: '0644'
          notify: Refresh RedHat Console

  # ==============================================================================
  # HANDLERS (Run only if changes were made)
  # ==============================================================================
  handlers:
    - name: Refresh Debian Console
      ansible.builtin.command: setupcon
      # If setupcon still fails for some obscure reason, we don't want to crash the play
      ignore_errors: true 

    - name: Refresh RedHat Console
      # Direct kernel load command for immediate effect
      ansible.builtin.shell: loadkeys uk
      ignore_errors: true
