---
- name: Set Universal Keyboard Layout (File-Based Method)
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # ==============================================================================
    # 1. DEBIAN / UBUNTU FAMILY
    #    Uses /etc/default/keyboard with code "gb"
    # ==============================================================================
    - name: Configure Debian/Ubuntu Keyboard
      when: ansible_os_family == "Debian"
      block:
        - name: Ensure /etc/default/keyboard exists
          ansible.builtin.file:
            path: /etc/default/keyboard
            state: touch
            mode: '0644'

        - name: Set XKBLAYOUT to gb (Debian Standard)
          ansible.builtin.lineinfile:
            path: /etc/default/keyboard
            regexp: '^XKBLAYOUT='
            line: 'XKBLAYOUT="gb"'

        - name: Apply changes immediately (setupcon)
          ansible.builtin.command: setupcon
          changed_when: false
          # updates the current console cached fonts/keymaps

    # ==============================================================================
    # 2. REDHAT / ROCKY / SUSE FAMILY
    #    Uses /etc/vconsole.conf with code "uk" (Legacy standard for VC)
    # ==============================================================================
    - name: Configure RHEL/Rocky/SUSE Keyboard
      when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"
      block:
        - name: Ensure /etc/vconsole.conf exists
          ansible.builtin.file:
            path: /etc/vconsole.conf
            state: touch
            mode: '0644'

        - name: Set KEYMAP to uk (RHEL/SUSE Standard)
          ansible.builtin.lineinfile:
            path: /etc/vconsole.conf
            regexp: '^KEYMAP='
            line: 'KEYMAP="uk"'

        # This service loads the settings from vconsole.conf into the kernel
        - name: Apply changes to current session
          ansible.builtin.service:
            name: systemd-vconsole-setup
            state: restarted
          ignore_errors: true
