---
- name: Set Universal Locale & Keyboard to UK
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # ==============================================================================
    # 1. DEBIAN / UBUNTU / KALI
    #    Method: edit /etc/default/keyboard
    # ==============================================================================
    - name: Handle Debian/Ubuntu Family
      when: ansible_os_family == "Debian"
      block:
        - name: Ensure 'console-setup' and locales are installed
          ansible.builtin.apt:
            name: 
              - console-setup
              - locales
            state: present
            update_cache: yes
            cache_valid_time: 3600

        # Debian Specific: Generate the locale if missing
        - name: Generate en_GB.UTF-8 locale
          ansible.builtin.locale_gen:
            name: en_GB.UTF-8
            state: present

        - name: Set Keyboard Layout (XKBLAYOUT) to gb
          ansible.builtin.lineinfile:
            path: /etc/default/keyboard
            regexp: '^XKBLAYOUT='
            line: 'XKBLAYOUT="gb"'
            create: yes
            mode: '0644'
          notify: Refresh Debian Console

    # ==============================================================================
    # 2. REDHAT / ROCKY / SUSE
    #    Method: localectl (Systemd standard)
    # ==============================================================================
    - name: Handle RedHat/Suse Family
      when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"
      block:
        - name: Ensure English language packs are installed
          ansible.builtin.dnf:
            name: langpacks-en
            state: present
          ignore_errors: true # In case the package name differs on older versions

        # 1. Set the System Language (The command you found)
        - name: Set System Locale to British English (en_GB)
          ansible.builtin.command: localectl set-locale LANG=en_GB.utf8
          changed_when: false # localectl handles state, running it again is harmless

        # 2. Set the Keyboard Layout (The 'uk' map is standard for RHEL console)
        - name: Set Console Keyboard Layout to UK
          ansible.builtin.command: localectl set-keymap uk
          changed_when: false

  # ==============================================================================
  # HANDLERS
  # ==============================================================================
  handlers:
    - name: Refresh Debian Console
      ansible.builtin.command: setupcon
      ignore_errors: true